"""
ZeroDB init command - Interactive setup wizard

Provides an interactive CLI wizard to:
- Check prerequisites
- Configure environment
- Create data directories
- Start services
- Verify installation

Refs #1132
"""
import typer
import subprocess
import time
from pathlib import Path
from typing import Optional, Dict, Any
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
from rich.prompt import Prompt, Confirm

# Import prerequisite checks
import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from zerodb.utils.prerequisites import (
    check_prerequisites,
    check_docker_installed,
    check_docker_desktop_running,
    check_all_ports,
    check_disk_space
)
from zerodb.utils.branding import print_logo, print_welcome_message

app = typer.Typer(help="Initialize ZeroDB Local environment")
console = Console()

# Project root (parent of cli directory)
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent.resolve()
DOCKER_COMPOSE_FILE = PROJECT_ROOT / "docker-compose.yml"
DATA_DIR = PROJECT_ROOT / "data"


def get_default_config() -> Dict[str, str]:
    """
    Get default configuration values

    Returns:
        dict: Default configuration
    """
    return {
        'project_name': 'zerodb-local',
        'postgres_db': 'zerodb_local',
        'postgres_user': 'zerodb',
        'postgres_password': 'localpass',
        'minio_access_key': 'minioadmin',
        'minio_secret_key': 'minioadmin',
        'embeddings_model': 'BAAI/bge-small-en-v1.5',
        'embeddings_device': 'cpu',
        'log_level': 'info'
    }


def validate_project_name(name: str) -> bool:
    """
    Validate project name

    Args:
        name: Project name to validate

    Returns:
        bool: True if valid
    """
    if not name:
        return False
    if ' ' in name:
        return False
    if any(c in name for c in ['@', '#', '$', '%', '^', '&', '*', '(', ')']):
        return False
    return True


def create_data_directories(project_root: Path):
    """
    Create required data directories

    Args:
        project_root: Project root path
    """
    data_dir = project_root / "data"

    directories = [
        data_dir / "postgres",
        data_dir / "qdrant",
        data_dir / "minio",
        data_dir / "redpanda",
        data_dir / "embeddings" / "models"
    ]

    for directory in directories:
        directory.mkdir(parents=True, exist_ok=True)


def create_env_file(env_path: Path, config: Dict[str, str]):
    """
    Create .env file with configuration

    Args:
        env_path: Path to .env file
        config: Configuration dictionary
    """
    env_content = f"""# ZeroDB Local Environment Configuration
# Generated by zerodb init

# PostgreSQL Configuration
POSTGRES_DB={config['postgres_db']}
POSTGRES_USER={config['postgres_user']}
POSTGRES_PASSWORD={config['postgres_password']}

# MinIO Configuration
MINIO_ACCESS_KEY={config['minio_access_key']}
MINIO_SECRET_KEY={config['minio_secret_key']}

# Embeddings Configuration
EMBEDDINGS_MODEL={config['embeddings_model']}
EMBEDDINGS_DEVICE={config['embeddings_device']}

# Environment
ZERODB_ENV=local
LOG_LEVEL={config['log_level']}
"""

    env_path.write_text(env_content)


def start_services(project_root: Path):
    """
    Start Docker Compose services

    Args:
        project_root: Project root path

    Raises:
        subprocess.CalledProcessError: If docker-compose fails
    """
    cmd = ["docker-compose", "-f", str(DOCKER_COMPOSE_FILE), "up", "-d"]

    result = subprocess.run(
        cmd,
        cwd=str(project_root),
        capture_output=True,
        text=True,
        check=True
    )


def wait_for_services_healthy(timeout: int = 60) -> bool:
    """
    Wait for services to become healthy

    Args:
        timeout: Timeout in seconds

    Returns:
        bool: True if all services are healthy
    """
    import requests

    start_time = time.time()
    health_url = "http://localhost:8000/health"

    while time.time() - start_time < timeout:
        try:
            response = requests.get(health_url, timeout=5)
            if response.status_code == 200:
                data = response.json()
                if data.get('status') == 'healthy':
                    return True
        except Exception:
            pass

        time.sleep(2)

    return False


def monitor_startup(project_root: Path):
    """
    Monitor service startup with progress indicator

    Args:
        project_root: Project root path
    """
    services = [
        "postgres",
        "qdrant",
        "minio",
        "redpanda",
        "embeddings",
        "zerodb-api",
        "dashboard"
    ]

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        console=console
    ) as progress:
        for service in services:
            task = progress.add_task(f"Starting {service}...", total=100)
            time.sleep(0.5)  # Simulate startup time
            progress.update(task, completed=100)


def run_setup_wizard(interactive: bool = True) -> Dict[str, str]:
    """
    Run interactive setup wizard

    Args:
        interactive: Whether to prompt for input

    Returns:
        dict: Configuration
    """
    config = get_default_config()

    if interactive:
        console.print("\n[bold cyan]Configuration[/bold cyan]")
        console.print("Press Enter to use default values\n")

        project_name = Prompt.ask(
            "Project name",
            default=config['project_name']
        )
        if validate_project_name(project_name):
            config['project_name'] = project_name

        config['postgres_db'] = Prompt.ask(
            "PostgreSQL database name",
            default=config['postgres_db']
        )

        config['postgres_user'] = Prompt.ask(
            "PostgreSQL user",
            default=config['postgres_user']
        )

    return config


@app.command()
def init(
    yes: bool = typer.Option(False, "--yes", "-y", help="Skip confirmation prompts"),
    interactive: bool = typer.Option(True, "--interactive/--no-interactive", help="Run interactive wizard"),
    start_services: bool = typer.Option(True, "--start-services/--no-start-services", help="Start services after setup")
):
    """
    Initialize ZeroDB Local environment with interactive setup wizard
    """
    try:
        # Display logo and welcome
        print_logo(console)
        print_welcome_message(console, duration="60 seconds")

        # Welcome message
        console.print(Panel(
            "[bold cyan]ZeroDB Local Setup Wizard[/bold cyan]\n\n"
            "This wizard will guide you through setting up your local ZeroDB environment.\n"
            "It will check prerequisites, configure settings, and start services.",
            title="Welcome",
            border_style="cyan"
        ))

        # Step 1: Check prerequisites
        console.print("\n[bold]Step 1:[/bold] Checking prerequisites...\n")

        prereq_results = check_prerequisites(PROJECT_ROOT)

        # Display results in table
        table = Table(title="Prerequisite Checks")
        table.add_column("Check", style="cyan")
        table.add_column("Status", style="white")
        table.add_column("Details", style="dim")

        # Docker
        docker_status = "[green]✓ Installed[/green]" if prereq_results['docker'] else "[red]✗ Not found[/red]"
        table.add_row("Docker", docker_status, "")

        # Docker running
        if prereq_results['docker']:
            docker_running_status = "[green]✓ Running[/green]" if prereq_results['docker_running'] else "[red]✗ Not running[/red]"
            table.add_row("Docker Desktop", docker_running_status, "")

        # Python
        python_status = "[green]✓ Compatible[/green]" if prereq_results['python']['supported'] else "[red]✗ Incompatible[/red]"
        table.add_row("Python Version", python_status, prereq_results['python']['version'])

        # Ports
        ports_status = "[green]✓ Available[/green]" if prereq_results['ports']['all_available'] else "[red]✗ In use[/red]"
        ports_detail = ""
        if not prereq_results['ports']['all_available']:
            ports_detail = f"Ports in use: {', '.join(map(str, prereq_results['ports']['in_use']))}"
        table.add_row("Required Ports", ports_status, ports_detail)

        # Disk space
        disk_status = "[green]✓ Sufficient[/green]" if prereq_results['disk_space']['sufficient'] else "[yellow]⚠ Low[/yellow]"
        disk_detail = f"{prereq_results['disk_space']['free_gb']}GB free"
        table.add_row("Disk Space", disk_status, disk_detail)

        console.print(table)

        # Handle errors
        if not prereq_results['all_passed']:
            console.print("\n[red]✗ Prerequisites check failed[/red]\n")
            for error in prereq_results['errors']:
                console.print(f"  [red]•[/red] {error}")

            console.print("\n[dim]For troubleshooting help, visit: https://docs.ainative.studio/zerodb/troubleshooting[/dim]")
            raise typer.Exit(1)

        # Show warnings
        if prereq_results['warnings']:
            console.print("\n[yellow]⚠ Warnings:[/yellow]")
            for warning in prereq_results['warnings']:
                console.print(f"  [yellow]•[/yellow] {warning}")

        console.print("\n[green]✓ All prerequisites passed[/green]\n")

        # Step 2: Configuration
        console.print("[bold]Step 2:[/bold] Configuration\n")

        config = run_setup_wizard(interactive=interactive and not yes)

        # Display configuration summary
        config_table = Table(title="Configuration Summary")
        config_table.add_column("Setting", style="cyan")
        config_table.add_column("Value", style="white")

        for key, value in config.items():
            if 'password' not in key.lower() and 'secret' not in key.lower():
                config_table.add_row(key.replace('_', ' ').title(), value)
            else:
                config_table.add_row(key.replace('_', ' ').title(), "***")

        console.print(config_table)

        # Confirm before proceeding
        if not yes and interactive:
            if not Confirm.ask("\nProceed with this configuration?", default=True):
                console.print("[yellow]Setup cancelled[/yellow]")
                raise typer.Exit(0)

        # Step 3: Create directories and files
        console.print("\n[bold]Step 3:[/bold] Creating directories and configuration files...\n")

        with console.status("[cyan]Creating data directories..."):
            create_data_directories(PROJECT_ROOT)
        console.print("[green]✓[/green] Data directories created")

        env_file = PROJECT_ROOT / ".env"
        with console.status("[cyan]Creating .env file..."):
            create_env_file(env_file, config)
        console.print(f"[green]✓[/green] Configuration file created: {env_file}")

        # Step 4: Start services
        if start_services:
            console.print("\n[bold]Step 4:[/bold] Starting services...\n")

            with console.status("[cyan]Starting Docker containers..."):
                start_services(PROJECT_ROOT)

            console.print("[green]✓[/green] Docker containers started")

            console.print("\n[cyan]Waiting for services to become healthy...[/cyan]")
            console.print("[dim]This may take 30-60 seconds...[/dim]\n")

            monitor_startup(PROJECT_ROOT)

            if wait_for_services_healthy(timeout=90):
                console.print("\n[green]✓ All services are healthy[/green]")
            else:
                console.print("\n[yellow]⚠ Services started but health check timed out[/yellow]")
                console.print("Run '[cyan]zerodb status[/cyan]' to check service status")

        # Success message
        console.print(Panel(
            "[bold green]Setup Complete![/bold green]\n\n"
            "Your ZeroDB Local environment is ready.\n\n"
            "[bold]Next steps:[/bold]\n"
            "  • Check status: [cyan]zerodb status[/cyan]\n"
            "  • View logs: [cyan]zerodb logs[/cyan]\n"
            "  • Open dashboard: [cyan]zerodb dashboard[/cyan]\n"
            "  • View help: [cyan]zerodb --help[/cyan]",
            title="Success",
            border_style="green"
        ))

    except KeyboardInterrupt:
        console.print("\n\n[yellow]Setup cancelled by user[/yellow]")
        raise typer.Exit(130)
    except Exception as e:
        console.print(f"\n[red]Error during setup: {str(e)}[/red]")
        raise typer.Exit(1)


if __name__ == "__main__":
    app()
